name: Deploy Content to scew1 [3c91fe74-0355-4ee7-8748-07e6efc8fa8c]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-3c91fe74-0355-4ee7-8748-07e6efc8fa8c.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on:
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-3c91fe74-0355-4ee7-8748-07e6efc8fa8c.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'socrg'
      workspaceName: 'scew1'
      workspaceId: '329544dc-9ea9-4a9d-9d75-e0516a3a56dc'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      contentTypes: 'Watchlist'
      branch: 'main'
      sourceControlId: '3c91fe74-0355-4ee7-8748-07e6efc8fa8c'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
    permissions:
      contents: write
      id-token: write # Require write permission to Fetch an OIDC token.

    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_3c91fe7403554ee7874807e6efc8fa8c }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_3c91fe7403554ee7874807e6efc8fa8c }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_3c91fe7403554ee7874807e6efc8fa8c }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v2
      if: ${{ steps.login1.outcome=='failure' }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_3c91fe7403554ee7874807e6efc8fa8c }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_3c91fe7403554ee7874807e6efc8fa8c }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_3c91fe7403554ee7874807e6efc8fa8c }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30

    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v2
      if: ${{ steps.login2.outcome=='failure'  }}
      with:
        client-id: ${{ secrets.AZURE_SENTINEL_CLIENTID_3c91fe7403554ee7874807e6efc8fa8c }}
        tenant-id: ${{ secrets.AZURE_SENTINEL_TENANTID_3c91fe7403554ee7874807e6efc8fa8c }}
        subscription-id: ${{ secrets.AZURE_SENTINEL_SUBSCRIPTIONID_3c91fe7403554ee7874807e6efc8fa8c }}
        environment: 'AzureCloud'
        audience: api://AzureADTokenExchange
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy Content to Microsoft Sentinel
      uses: azure/powershell@v2
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-3c91fe74-0355-4ee7-8748-07e6efc8fa8c.ps1